name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 0 * * 3'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - uses: coursier/cache-action@v5
    - run: sbt "onFailure +test:compile" "+test:compile"
    - sbt
      "scalafmtCheck"
      "scalafmtCheckAll"
      "+test"
      "+core/publishLocal"
      "++2.12.12"
      "tests/scripted"
